In [1]:
import numpy as np
import pandas as pd

In [2]:

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
# You would have to craete a seperate list for defining the labels 
columns = ["Name" , "Age" , "City" , "Salary" ]
df = pd.DataFrame(data , columns = columns)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**ADDING AND REMOVING A NEW COLUMN**

In [10]:
df["Designation"] = ["Engineer" , "Doctor" , "Lawyer" , "Developer"]

In [11]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000   Developer

In [15]:
df.drop("Designation" , axis = 1)
# To completely remove  the designation column use { inplace = True }

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000   Developer

**EXTRACTING DATA BASED UPON CONDITIONS**

In [18]:
# Extract people from the dataset whose age is above 25
df[df["Age"] > 25  ]

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000   Developer

In [20]:
# Extract people from dataset who live in NewYork and London
df[df["City"].isin(["New York" , "London"])]

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
3  Linda   42    London   85000   Developer

In [21]:
# Extract people from dataset who do not live in NewYork and London
df[~df["City"].isin(["New York" , "London"])]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000      Doctor
2  Peter   29  Berlin   62000      Lawyer

In [22]:
#I only want poeple whose age is above 30 and their city must be paris
df[(df["City"] == "Paris") & (df["Age"] > 30 )]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000      Doctor

In [34]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
sum = df.isna().sum()
sum

A    1
B    0
C    2
D    3
dtype: int64

In [29]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [30]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [33]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [37]:
values = {
    "A" : 25,
    "B" : 35,
    "C" : 65,
    "D" : 45
}
df.fillna(value = values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  45.0
2  25.0  3   3.0  45.0
3   4.0  4  65.0  45.0
4   5.0  5  65.0   5.0

In [38]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [39]:
df.fillna(df.median())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [40]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [41]:
# Use inplace = True to implement the results permanently in the dataset

In [44]:
df = pd.read_excel(r"C:\Users\alexf\OneDrive\Documents\Pandas Tutorial\Customer Call List.xlsx")
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexf\\OneDrive\\Documents\\Pandas Tutorial\\Customer Call List.xlsx'